### PR TITLE
Use io.open instead of codecs.open

### PR DESCRIPTION
**Pull request by methane**

### CODE REVIEW

**Comment by kennethreitz** [comment]
I'm not familiar with `io.open`. What benefit does this provide?

**Comment by methane** [comment]
`io.open` is builtin `open` on Python 3.
`io.open` is recommended way to open file since Python 2.6.

Since Python 2.7, io.open returns C implementation TextIOWrapper, which is faster than codecs.open.

`codecs.open` is required for projects only supporting Python 2.5.

**Comment by kennethreitz** [comment]
and it supports `encoding`

**Comment by kennethreitz** [comment]
✨🍰✨

**Pull request merged**
