### PR TITLE
Fixing typo and making License a variable

### PR DESCRIPTION
**Pull request by alexanderepstein**
Typo was causing syntax error and made license a variable.

### CODE REVIEW

**Comment by kennethreitz** [comment]
License should be left the same, or the Trove Identifier should also be updated from this variable!

**Comment by alexanderepstein** [comment]
Are you referring to line 58 when you say the trove identifier?

**Comment by kennethreitz** [comment]
Line 59/60 :)

**Comment by alexanderepstein** [comment]
I wasn't going to change that just in case the license isn't OSI approved so that the user doesn't just add this by accident but I can make that use the variable as well if you'd like.

**Comment by kennethreitz** [comment]
well, let's either insert it in, or let's just leave the LICENSE as is. I vote for as-is.

**Comment by alexanderepstein** [comment]
I will just revert the license to as it was if you like it better that way :+1:

**Comment by kennethreitz** [comment]
✨🍰✨

**Pull request merged**
