### PR TITLE
Fix missing comma

### LINKED ISSUE #42: Missing comma in setup kwargs
https://github.com/kennethreitz/setup.py/blob/71dc482c94749327732237746e24d1722705941f/setup.py#L92

Looks like there should be a comma here

### PR DESCRIPTION
**Pull request by MasterOdin**
Fixes #42

### CODE REVIEW

**Comment by carsonip** [comment]
Oops, I created an identical PR as yours.

**Comment by devxpy** [comment]
Me too xD

**Comment by aljp** [comment]
I was about to make a PR 🤒

**Comment by bildzeitung** [comment]
Just encountered this issue myself; thanks for having a PR already for it!

**Pull request merged**
